permalink: /:year/:month/:day/:title.html
markdown: kramdown
highlighter: pygments 
kramdown:
  input: GFM

# 作者信息
author: 
  name: 凨
  email: liyunf81@hotmail.com
  weibo: http://weibo.com/2163612074/
  github: https://github.com/liyunf81

# 站点信息
title: 凨 
description: 凨的地盘
url: http://liyunf81.github.io
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: http://7x2xd3.com1.z0.glb.clouddn.com/my.jpg
favicon: http://7x2xd3.com1.z0.glb.clouddn.com/favicon.ico

# google analytics 设置
ga:
  id: UA-60587110-1
  url: fengyalife.com

# disqus 设置
disqus:
  shortname: fengya
